#!/usr/bin/env bash

# get bash colors and styles here:
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
    output=$(eval "$3" 2>&1)
    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}NOK!${C_RESET}\n\n$output"
        echo -e "If you want to bypass pre commit hook, add '--no-verify' to your commit command"

        exit 1
    fi
}

modified="git diff --diff-filter=M --name-only --cached ':(exclude)deploy.php' | grep \".php$\""
phpcsfixer="docker-compose exec -T php gosu kop php ./vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix src"

__run "1/3" "php lint" "${modified} | xargs -r docker-compose exec -T php gosu kop php -l"
__run "2/3" "cs fixer" "${phpcsfixer}"
__run "3/3" "phpstan" "${modified} | xargs -r docker-compose exec -T php gosu kop php ./vendor/bin/phpstan analyse --level=8"
