hosts:
    staging:
        keep_releases: 3
        stage: staging
        hostname: 51.38.178.29
        remote_user: staging-kop
        http_user: www-data
        deploy_path: /home/staging-kop/staging-api.king-of-paddock.fr
        url: https://staging-api.king-of-paddock.fr
        bin/php: "php8.3 -d memory_limit=256M"
        multiplexing: false
        writable_mode: chmod

    prod:
        keep_releases: 3
        stage: prod
        hostname: 51.38.178.29
        remote_user: kingofpaddock
        http_user: www-data
        deploy_path: /home/kingofpaddock/api.king-of-paddock.fr
        url: https://api.kingofpaddock.com
        bin/php: "/usr/bin/php -d memory_limit=256M"
        multiplexing: false
        writable_mode: chmod
